version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7
      
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run: yarn validate